<div class="container-fluid">
	<h1 class="my-4">Fucntion 1</h1>
	<div class="row my-4">
	<?php foreach ($list as $key => $value): ?>
		<div class="col-4 my-4"><a href="#" class="btn btn-block btn-lg btn-primary"><?php echo $value;?></a></div>
	<?php endforeach; ?>
	</div>
</div>

<footer class="footer">
	<div class  ="container">
		<div class="float-left d-inline">
			<<
		</div>

		<div class="float-right d-inline">
			>>
		</div>
	</div>
</footer>
