<div class="container-fluid">
	<h1 class="my-4">&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;</h1>
	<div class="row my-4">
		<div class="col-4"><a href="/f1.php" class="btn btn-block btn-lg btn-primary">Function 1</a></div>
		<div class="col-4"><a href="/f2.php" class="btn btn-block btn-lg btn-primary">Function 2</a></div>
		<div class="col-4"><a href="/f3.php" class="btn btn-block btn-lg btn-primary">Function 3</a></div>
	</div>
	<div class="row my-4">
		<div class="col-4"><a href="/f4.php" class="btn btn-block btn-lg btn-primary">Function 4</a></div>
		<div class="col-4"><a href="/f5.php" class="btn btn-block btn-lg btn-primary">Function 5</a></div>
		<div class="col-4"><a href="/f6.php" class="btn btn-block btn-lg btn-primary">Function 6</a></div>
	</div>
</div>	